<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 1" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="D:\YXW.FILE\code\dataclearn\src\clearnToMatix1.py" status="error" test="clearnToMatix1" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\sjzx\.p2\pool\plugins\org.python.pydev_5.9.2.201708151115\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "D:\YXW.FILE\code\dataclearn\src\clearnToMatix1.py", line 25, in <module>
    li.append(ma.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
ERROR: Module: clearnToMatix1 could not be imported (file: D:\YXW.FILE\code\dataclearn\src\clearnToMatix1.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="dataclearn clearnToMatix1.py (1)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
